### ISSUE TITLE
Make framework independent of async runtime provider.

### ISSUE THREAD

**Issue by humb1t** [tg-rs/carapax#62]
Right now `carapax` and `tg-bot` works only with `tokio` runtime:
```
thread 'async-std/executor' panicked at 'not currently running on the Tokio runtime.', /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:63:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/option.rs:347
  15: tokio::runtime::handle::Handle::current
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:63
  16: tokio::runtime::blocking::pool::spawn_blocking
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/blocking/pool.rs:65
  17: tokio::task::blocking::spawn_blocking
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/blocking.rs:69
  18: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/dns.rs:120
  19: <S as hyper::client::connect::dns::sealed::Resolve>::resolve
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/dns.rs:332
  20: hyper::client::connect::dns::resolve::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/dns.rs:342
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  22: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  23: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/http.rs:307
  24: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  25: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  26: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/http.rs:248
  27: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/future/future.rs:118
  29: <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/connect/http.rs:388
  30: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/either.rs:62
  31: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  32: <hyper_rustls::connector::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:126
  33: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/future/future.rs:118
  35: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  36: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/connect.rs:371
  37: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  38: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  39: reqwest::connect::with_timeout::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/connect.rs:500
  40: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:44
  41: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/future/future.rs:118
  42: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/service/oneshot.rs:58
  43: <F as futures_core::future::TryFuture>::try_poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  44: <futures_util::future::try_future::map_err::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/map_err.rs:43
  45: <F as futures_core::future::TryFuture>::try_poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  46: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/try_chain.rs:53
  47: <futures_util::future::try_future::and_then::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/and_then.rs:46
  48: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/either.rs:62
  49: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/common/lazy.rs:59
  50: futures_util::future::future::FutureExt::poll_unpin
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  51: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/select.rs:64
  52: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/chain.rs:44
  53: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/then.rs:44
  54: <F as futures_core::future::TryFuture>::try_poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  55: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/try_chain.rs:53
  56: <futures_util::future::try_future::and_then::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/and_then.rs:46
  57: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/mod.rs:253
  58: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/poll_fn.rs:54
  59: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/future/future.rs:118
  60: <hyper::client::ResponseFuture as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/client/mod.rs:604
  61: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/async_impl/client.rs:1276
  62: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/async_impl/client.rs:1255
  63: std::future::poll_with_tls_context
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/future.rs:99
  64: tgbot::api::Api::execute::{{closure}}
             at /home/humb1t/.cargo/registry/src/github.com-1ecc6299db9ec823/tgbot-0.7.1/src/api.rs:158
```
It will be great to be `runtime` independent.

**Comment by rossnomann** [comment]
In order to be runtime-agnostic we need libraries which are also runtime-agnostic. HTTP client with proxy and multipart support, file I/O, etc. At the current time I don't know such libraries. So, to support async-std I need to write a compatibility layer by myself. It's very hard and complicated task. I suggest waiting when ecosystem will be ready to be runtime-agnostic. Currently all necessary libraries have tokio support only and I see no reason to support async-std if dependencies do not support it.
